services:
  # Redis Private Service
  - type: pserv
    name: evolution-redis
    runtime: image
    image:
      url: redis:alpine
    region: ohio
    plan: free
    ipAllowList: [] # Private network only

  # Evolution API Web Service
  - type: web
    name: evolution-api
    runtime: docker
    region: ohio
    plan: starter
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AUTHENTICATION_API_KEY
        generateValue: true
      - key: SERVER_URL
        value: https://evolution-api.onrender.com
      - key: DATABASE_PROVIDER
        value: psql_bouncer
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_HkoXx5AyuTq7@ep-sweet-tree-a5afsnqw-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require&schema=public&connection_limit=20&pool_timeout=30
      - key: DATABASE_CONNECTION_URI
        value: postgresql://neondb_owner:npg_HkoXx5AyuTq7@ep-sweet-tree-a5afsnqw.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require&schema=public
      - key: DATABASE_ENABLED
        value: "true"
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        value: redis://evolution-redis:6379
      - key: CACHE_LOCAL_ENABLED
        value: "true"
      - key: LOG_LEVEL
        value: ERROR,WARN,DEBUG,INFO
      - key: LOG_COLOR
        value: "true"
      - key: DEL_INSTANCE
        value: "false"
      - key: STORE_MESSAGES
        value: "true"
      - key: STORE_CONTACTS
        value: "true"
      - key: STORE_CHATS
        value: "true"
      - key: CORS_ORIGIN
        value: "*"
      - key: CORS_METHODS
        value: POST,GET,PUT,DELETE
      - key: CORS_CREDENTIALS
        value: "true"
    healthCheckPath: /
